version: '3'
services:
  jenkins_fil:
    build: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sonar:
    image: "filler36/sonar:2"
    ports:
      - "9000:9000"
  artifactory_fil:
    image: "docker.bintray.io/jfrog/artifactory-oss:latest"
    ports:
      - "8081:8081"
